// Copyright 2026 Gert Nutterts
// SPDX-License-Identifier: Apache-2.0

package burstein

import (
	"context"
	"errors"
	"fmt"
	"sort"

	"github.com/gnutterts/chesspairing"
	"github.com/gnutterts/chesspairing/pairing/swisslib"
	"github.com/gnutterts/chesspairing/scoring/standard"
)

var (
	// ErrTooFewPlayers is returned when there aren't enough active players.
	ErrTooFewPlayers = errors.New("burstein pairing requires at least 2 active players")
	// ErrNoPairingPossible is returned when no valid pairing can be found.
	ErrNoPairingPossible = errors.New("no valid pairing exists for the remaining players")
	// ErrBracketTooLarge is returned when exhaustive floater enumeration reaches its safety limit.
	ErrBracketTooLarge = errors.New("bracket floater enumeration exceeds the safety limit")
)

// Pair generates pairings according to FIDE C.04.4.2.
func (p *Pairer) Pair(ctx context.Context, state *chesspairing.TournamentState) (*chesspairing.PairingResult, error) {
	if err := ctx.Err(); err != nil {
		return nil, err
	}
	if IsSeedingRound(state.CurrentRound, p.totalRounds(state)) {
		return p.dutchSeedingPair(ctx, state)
	}
	return p.postSeedingPair(ctx, state)
}

// dutchSeedingPair implements C.04.4.2 Article 1.6.
func (p *Pairer) dutchSeedingPair(ctx context.Context, state *chesspairing.TournamentState) (*chesspairing.PairingResult, error) {
	return p.pairDutchSeeding(ctx, state)
}

// postSeedingPair implements C.04.4.2 Articles 1.7 to 5.2.
func (p *Pairer) postSeedingPair(ctx context.Context, original *chesspairing.TournamentState) (*chesspairing.PairingResult, error) {
	state, preAssigned := swisslib.FilterPreAssignedByes(original)
	players, err := swisslib.BuildPlayerStates(state)
	if err != nil {
		return nil, err
	}
	if len(players) == 0 {
		if len(preAssigned) == 0 {
			return nil, ErrTooFewPlayers
		}
		result := &chesspairing.PairingResult{Byes: preAssigned}
		return result, validateResult(original, result)
	}
	if len(players) == 1 {
		if players[0].PABIneligible.Any() {
			return nil, noPABError()
		}
		result := &chesspairing.PairingResult{Byes: append(preAssigned, chesspairing.ByeEntry{PlayerID: players[0].ID, Type: chesspairing.ByePAB})}
		return result, validateResult(original, result)
	}
	if p.opts.Acceleration != nil && *p.opts.Acceleration == "baku" {
		winPoints := standard.WinPoints(state.ScoringConfig.Options)
		swisslib.ApplyBakuAcceleration(winPoints, players, state.CurrentRound, p.totalRounds(state), swisslib.BakuGASize(len(original.Players)))
	}
	active := make([]*swisslib.PlayerState, len(players))
	indices := make(map[string]OppositionIndex, len(players))
	for i := range players {
		active[i] = &players[i]
		indices[players[i].ID] = ComputeOppositionIndex(&players[i], state)
	}
	// Article 5.2.1 numbers entered players before the pairing-allocated bye
	// is removed from this round's pairing.
	parity := colorParityRanks(original, active)
	forbidden := buildForbiddenPairSet(p.opts.ForbiddenPairs)
	var pab *swisslib.PlayerState
	if len(active)%2 != 0 {
		pab = choosePAB(active, indices, forbidden, state)
		if pab == nil {
			return nil, noPABError()
		}
		active = removePlayer(active, pab.ID)
	}
	states := make([]swisslib.PlayerState, len(active))
	for i, player := range active {
		states[i] = *player
	}
	groups := swisslib.BuildScoreGroups(states)
	pairs, err := pairPostSeedingBrackets(ctx, groups, indices, forbidden)
	if err != nil {
		if errors.Is(err, ErrNoPairingPossible) || errors.Is(err, ErrBracketTooLarge) {
			return nil, &chesspairing.PairingError{Kind: chesspairing.PairingImpossible, System: "burstein", Err: err}
		}
		return nil, err
	}
	pairings := make([]chesspairing.GamePairing, len(pairs))
	for i, pair := range pairs {
		white, black := allocateBursteinColor(pair[0], pair[1], indices, parity, parseTopSeedColor(p.opts.TopSeedColor))
		pairings[i] = chesspairing.GamePairing{Board: i + 1, WhiteID: white, BlackID: black}
	}
	result := &chesspairing.PairingResult{Pairings: pairings, Byes: append([]chesspairing.ByeEntry{}, preAssigned...), Notes: []string{"Post-seeding round " + fmt.Sprint(state.CurrentRound) + " (opposition index ranking)"}}
	if pab != nil {
		result.Byes = append(result.Byes, chesspairing.ByeEntry{PlayerID: pab.ID, Type: chesspairing.ByePAB})
	}
	result.Notes = append(result.Notes, "Pairings generated by Burstein Swiss system (C.04.4.2)")
	return result, validateResult(original, result)
}

// choosePAB implements C.04.4.2 Article 3.1. Its lowest-score comparison is
// the pairing score, so it includes virtual acceleration points.
func choosePAB(players []*swisslib.PlayerState, indices map[string]OppositionIndex, forbidden map[[2]string]bool, state *chesspairing.TournamentState) *swisslib.PlayerState {
	candidates := append([]*swisslib.PlayerState{}, players...)
	sort.SliceStable(candidates, func(i, j int) bool {
		a, b := candidates[i], candidates[j]
		// Article 3.1.3 uses the pairing score, including virtual points.
		if a.PairingScore != b.PairingScore {
			return a.PairingScore < b.PairingScore
		}
		ga, gb := gamesPlayed(a.ID, state), gamesPlayed(b.ID, state)
		if ga != gb {
			return ga > gb
		}
		return rankingCompare(indices[a.ID], indices[b.ID]) > 0
	})
	for _, candidate := range candidates {
		if !candidate.PABIneligible.Any() && pairable(removePlayer(players, candidate.ID), forbidden) {
			return candidate
		}
	}
	return nil
}

func rankingCompare(a, b OppositionIndex) int {
	if a.Buchholz != b.Buchholz {
		if a.Buchholz > b.Buchholz {
			return -1
		}
		return 1
	}
	if a.SonnebornBerger != b.SonnebornBerger {
		if a.SonnebornBerger > b.SonnebornBerger {
			return -1
		}
		return 1
	}
	if a.TPN < b.TPN {
		return -1
	}
	if a.TPN > b.TPN {
		return 1
	}
	return 0
}

func removePlayer(players []*swisslib.PlayerState, id string) []*swisslib.PlayerState {
	out := make([]*swisslib.PlayerState, 0, len(players)-1)
	for _, player := range players {
		if player.ID != id {
			out = append(out, player)
		}
	}
	return out
}

func gamesPlayed(id string, state *chesspairing.TournamentState) int {
	games := 0
	for _, round := range completedRounds(state) {
		for _, game := range round.Games {
			if !game.IsForfeit && (game.WhiteID == id || game.BlackID == id) {
				games++
			}
		}
	}
	return games
}

func buildForbiddenPairSet(pairs [][]string) map[[2]string]bool {
	if len(pairs) == 0 {
		return nil
	}
	set := make(map[[2]string]bool, len(pairs))
	for _, pair := range pairs {
		if len(pair) == 2 {
			set[swisslib.CanonicalPairKey(pair[0], pair[1])] = true
		}
	}
	return set
}

func noPABError() error {
	return &chesspairing.PairingError{Kind: chesspairing.PairingNoPABCandidate, System: "burstein", Err: swisslib.ErrNoPABCandidate}
}

// allocateBursteinColor implements C.04.4.2 Article 5.2.
func allocateBursteinColor(a, b *swisslib.PlayerState, indices map[string]OppositionIndex, parity map[string]int, topSeed *swisslib.Color) (string, string) {
	pa, pb := swisslib.ComputeColorPreference(a.ColorHistory), swisslib.ComputeColorPreference(b.ColorHistory)
	grant := func(player *swisslib.PlayerState, color swisslib.Color) (string, string) {
		if color == swisslib.ColorWhite {
			return player.ID, other(player, a, b).ID
		}
		return other(player, a, b).ID, player.ID
	}
	if len(pa.PlayedColors) == 0 && len(pb.PlayedColors) == 0 {
		higher := a
		if rankingCompare(indices[a.ID], indices[b.ID]) > 0 {
			higher = b
		}
		initial := swisslib.ColorWhite
		if topSeed != nil {
			initial = *topSeed
		}
		if parity[higher.ID]%2 == 0 {
			initial = initial.Opposite()
		}
		return grant(higher, initial)
	}
	if pa.Color != nil && pb.Color != nil && *pa.Color != *pb.Color {
		return grant(a, *pa.Color)
	}
	if pa.Color != nil && pb.Color == nil {
		return grant(a, *pa.Color)
	}
	if pb.Color != nil && pa.Color == nil {
		return grant(b, *pb.Color)
	}
	if pa.Color != nil && pb.Color != nil && *pa.Color == *pb.Color {
		strength := func(preference swisslib.ColorPreference) int {
			switch {
			case preference.AbsolutePreference:
				return 2
			case preference.StrongPreference:
				return 1
			default:
				return 0
			}
		}
		as, bs := strength(pa), strength(pb)
		if as != bs || pa.ColorImbalance != pb.ColorImbalance {
			if as > bs || as == bs && pa.ColorImbalance > pb.ColorImbalance {
				return grant(a, *pa.Color)
			}
			return grant(b, *pb.Color)
		}
	}
	left, right := *a, *b
	if rankingCompare(indices[a.ID], indices[b.ID]) < 0 {
		left.TPN, right.TPN = 1, 2
	} else {
		left.TPN, right.TPN = 2, 1
	}
	return swisslib.AllocateColor(&left, &right, false, 1, topSeed, swisslib.FixedNumberParity)
}

func other(player, a, b *swisslib.PlayerState) *swisslib.PlayerState {
	if player == a {
		return b
	}
	return a
}

func parseTopSeedColor(opt *string) *swisslib.Color {
	if opt != nil && *opt == "black" {
		color := swisslib.ColorBlack
		return &color
	}
	return nil
}

func validateResult(state *chesspairing.TournamentState, result *chesspairing.PairingResult) error {
	if err := chesspairing.ValidatePairing(state, result); err != nil {
		if pairingErr, ok := err.(*chesspairing.PairingError); ok {
			pairingErr.System = "burstein"
			if pairingErr.Kind == chesspairing.PairingIncomplete {
				pairingErr.Partial = result
			}
		}
		return err
	}
	return nil
}

func (p *Pairer) totalRounds(state *chesspairing.TournamentState) int {
	if p.opts.TotalRounds != nil {
		return *p.opts.TotalRounds
	}
	total := state.CurrentRound
	if total < len(state.Rounds)+1 {
		total = len(state.Rounds) + 1
	}
	return total
}
